#!/usr/bin/env node
// decisions_owed.mjs — assemble the per-family evidence the user must rule on.
//
// WHY. Two blocking findings and ~600 legacy rows are stuck behind decisions
// only the business owner can make, and the standing rule is: bring the
// per-family EVIDENCE back before merging any customer-facing option. A bare
// "these 8 options collide" is not evidence — the owner needs to see which
// options, what they are called on the menu, what drawing backs each, and
// whether any drawing can tell them apart.
//
// This tool writes DECISIONS-OWED.md. It changes no catalog data and ships
// nothing; it only reads the generated index and the triage output.
//
// Usage: node tools/decisions_owed.mjs

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT = process.cwd();
const PUBLIC = path.join(ROOT, 'public');

const idx = JSON.parse(fs.readFileSync(path.join(PUBLIC, 'images/reports/repo-index.json'), 'utf8'));
const tri = JSON.parse(fs.readFileSync(path.join(PUBLIC, 'images/reports/collision-triage.json'), 'utf8'));
const led = JSON.parse(fs.readFileSync(path.join(PUBLIC, 'images/reports/legacy-visual-audit.json'), 'utf8'));

const labelOf = new Map();
const recOf = new Map();
for (const r of idx.records) {
  if (!r.inScope) continue;
  if (!labelOf.has(r.option)) labelOf.set(r.option, r.label);
  if (!recOf.has(r.option)) recOf.set(r.option, r);
}

const hashCache = new Map();
const hashOf = (rel) => {
  if (!rel) return null;
  if (hashCache.has(rel)) return hashCache.get(rel);
  let h = null;
  try {
    h = crypto.createHash('md5').update(fs.readFileSync(path.join(PUBLIC, rel.replace(/^\//, '')))).digest('hex');
  } catch {
    h = null;
  }
  hashCache.set(rel, h);
  return h;
};

const L = [];
L.push('# DECISIONS OWED — craft-option catalog');
L.push('');
L.push(`_Generated by \`tools/decisions_owed.mjs\` at ${new Date().toISOString()}. Reads only; changes nothing._`);
L.push('');
L.push('Each item below is blocked on a business ruling, not on engineering work.');
L.push('Regenerating images cannot resolve any of them — the source drawings are the limit.');
L.push('');

// ---------------------------------------------------------------- 1. loops-5
L.push('## 1. BLOCKING — `loops-5` shows the wrong photo to customers');
L.push('');
const loops5 = idx.records.filter((r) => r.option === 'loops-5');
const loopsStd = idx.records.filter((r) => r.option === 'loops-standard');
L.push(`\`5 Loops\` appears on **${loops5.length} product(s)** and has **no blueprint at all**.`);
L.push(`It currently displays \`${loops5[0]?.liveImage}\` — which is the photograph of`);
L.push(`\`${loopsStd[0]?.label}\`, backed by \`${loopsStd[0]?.illustration}\`.`);
L.push('');
L.push('A customer selecting "5 Loops" is shown a trouser with 7 loops. Belt-loop count is');
L.push('the entire discriminator of this field, so the image contradicts the choice exactly.');
L.push('');
L.push('**Your options:**');
L.push('- **(a) Source a 5-loop drawing** — then it generates and QCs normally.');
L.push('- **(b) Unwire the photo** — the option shows no image until a drawing exists. Honest, but blank.');
L.push('- **(c) Remove/merge the option** — if 5-loop is not genuinely offered.');
L.push('');
L.push('_Note: the project doctrine "a wrong photo beats no photo" was written for images awaiting');
L.push('a graded replacement. There is no path to a replacement here without a drawing, so that');
L.push('doctrine does not cover this case._');
L.push('');

// ------------------------------------------------- 2. source-limited families
L.push('## 2. BLOCKING — collision families no regeneration can fix');
L.push('');
const sl = tri.sourceLimited || [];
const slRows = sl.reduce((n, f) => n + (f.rowCount || 0), 0);
L.push(`**${sl.length} families · ${slRows} catalog rows.** In every one, the colliding options`);
L.push('point at a single blueprint (or byte-identical blueprints). QC scores fidelity *to the');
L.push('drawing*, so it actively drives these images together — spending credits here buys');
L.push('near-identical pictures that still legitimately pass.');
L.push('');
for (const f of sl) {
  L.push(`### \`${f.image}\``);
  L.push(`${f.optionCount} options · ${f.rowCount} rows · ${f.distinctBlueprintBytes} distinct drawing(s)`);
  L.push('');
  L.push('| option | menu label |');
  L.push('|---|---|');
  for (const o of f.options) L.push(`| \`${o}\` | ${labelOf.get(o) ?? '_(not in scope)_'} |`);
  L.push('');
  L.push(`_Why:_ ${f.why}`);
  L.push('');
  L.push('**Rule one of:** (a) source per-variant drawings · (b) drive the difference from spec');
  L.push('measurements and accept QC cannot verify it · (c) merge these into one menu option.');
  L.push('');
}

// ------------------------------------- 3. byte-identical drawings across rows
L.push('## 3. Byte-identical drawings behind options that must differ');
L.push('');
L.push('These are a **supplier data defect**, found during the legacy audit. Two options carry');
L.push('different labels and different prices on the menu, but their tech packs are the same');
L.push('file. No pipeline can separate them.');
L.push('');
const byBlueprintHash = new Map();
for (const r of idx.records) {
  if (!r.inScope || !r.illustration) continue;
  const h = hashOf(r.illustration);
  if (!h) continue;
  if (!byBlueprintHash.has(h)) byBlueprintHash.set(h, new Map());
  byBlueprintHash.get(h).set(r.option, r.illustration);
}
const dupDrawings = [...byBlueprintHash.entries()]
  .filter(([, m]) => m.size > 1)
  .map(([h, m]) => ({ h, opts: [...m.entries()] }))
  .sort((a, b) => b.opts.length - a.opts.length);
L.push(`**${dupDrawings.length} drawing(s) are reused across options that should be distinct.**`);
L.push('');
for (const d of dupDrawings.slice(0, 20)) {
  const paths = [...new Set(d.opts.map(([, p]) => p))];
  L.push(`- \`${d.h.slice(0, 12)}\` — ${d.opts.length} options, ${paths.length} filename(s)`);
  for (const [o, p] of d.opts) L.push(`    - \`${o}\` — ${labelOf.get(o) ?? ''} → \`${p}\``);
}
if (dupDrawings.length > 20) L.push(`- … ${dupDrawings.length - 20} more`);
L.push('');

// ---------------------------------------- 4. drawing contradicts catalog label
L.push('## 4. Drawings whose printed callout contradicts the catalog label');
L.push('');
L.push('Recorded as UNSURE by the legacy audit — deliberately neither pass nor fail. A wrong');
L.push('blueprint is invisible to QC (the more faithful the render, the higher it scores), so');
L.push('these must be settled by a human before any credits are spent on them.');
L.push('');
const unsure = led.rows.filter((r) => r.verdict === 'UNSURE');
L.push(`**${unsure.length} option(s) unresolved.**`);
L.push('');
for (const u of unsure) {
  const rec = recOf.get(u.option.split('/')[1]);
  L.push(`- **\`${u.option}\`** — ${labelOf.get(u.option.split('/')[1]) ?? ''}`);
  L.push(`    - drawing: \`${rec?.illustration ?? '?'}\``);
  L.push(`    - ${u.why}`);
}
L.push('');

// -------------------------------------- 5. blueprints that are not drawings
L.push('## 5. BLOCKING SPEND — options whose "blueprint" is not a drawing');
L.push('');
L.push('Measured from the pixels by `tools/blueprint_triage.mjs --all`, not from filenames.');
L.push('These files are catalogued as tech packs but are fabric-texture crops, icons or');
L.push('essentially blank frames. They cannot serve as a QC yardstick: QC scores fidelity');
L.push('*to the drawing*, so generating against one of these scores a render of a fabric');
L.push('swatch and can still pass.');
L.push('');
let triage = null;
try {
  triage = JSON.parse(fs.readFileSync(path.join(PUBLIC, 'images/reports/blueprint-triage.json'), 'utf8'));
} catch {
  /* triage not yet run */
}
if (!triage) {
  L.push('_Run `node tools/blueprint_triage.mjs --all` to populate this section._');
  L.push('');
} else {
  const badMap = new Map(
    triage.results
      .filter((e) => e.verdict === 'NOT_A_DRAWING' || e.verdict === 'SUSPECT')
      .map((e) => [e.blueprint, e.verdict]),
  );
  const affected = idx.records.filter((r) => r.inScope && r.illustration && badMap.has(r.illustration));
  const notStarted = affected.filter((r) => r.stage === 'not-started');
  const nsDistinct = new Set(notStarted.map((r) => r.option));
  const legacyAff = affected.filter((r) => r.stage === 'legacy-shipped-unverified');
  const est = Math.round(nsDistinct.size * 0.5 * 1.75);

  L.push(`- **${affected.length} in-scope rows** sit behind a SUSPECT or NOT_A_DRAWING blueprint.`);
  L.push(`- **${notStarted.length} of them are \`not-started\`** — ${nsDistinct.size} distinct images the`);
  L.push(`  next generation wave would have produced against unusable references.`);
  L.push(`- At 0.5 credits/image and the observed ~1.75 attempts per ship, that is`);
  L.push(`  **~${est} credits** that would have bought worthless images.`);
  L.push(`- A further **${legacyAff.length} legacy rows** cannot be audited against their drawing at all.`);
  L.push('');
  L.push('**Do not generate any of these until a real drawing exists.** For each affected');
  L.push('field, rule one of: (a) source the genuine supplier tech pack, (b) re-point the row');
  L.push('at a correct existing drawing (`tools/repoint_supplier_blueprints.mjs`), or');
  L.push('(c) accept label-only grading and mark the field QC-exempt.');
  L.push('');
  const byField = {};
  for (const r of affected) {
    const k = `${r.product} > ${r.field}`;
    byField[k] = (byField[k] || 0) + 1;
  }
  L.push('| product > field | affected rows |');
  L.push('|---|---|');
  for (const [k, v] of Object.entries(byField).sort((a, b) => b[1] - a[1]).slice(0, 25)) {
    L.push(`| ${k} | ${v} |`);
  }
  L.push('');
}

const dest = path.join(ROOT, 'DECISIONS-OWED.md');
fs.writeFileSync(dest, L.join('\n'));
console.log(`wrote ${path.relative(ROOT, dest)}`);
console.log(`  loops-5 rows:            ${loops5.length}`);
console.log(`  source-limited families: ${sl.length} (${slRows} rows)`);
console.log(`  duplicated drawings:     ${dupDrawings.length}`);
console.log(`  UNSURE options:          ${unsure.length}`);
